### PR TITLE
Added HTTPHeaderFields.h/.m

### PR DESCRIPTION
**Pull request by lquigley**
@vokal/ios-developers Thoughts on these changes to add header fields as strings?

### CODE REVIEW

**Comment by brockboland** [comment]
Seems like a good idea to me :+1:

**Comment by thoughtpalette** [comment]
:+1:

**Comment by designatednerd** [comment]
:+1: from me as well.

**Comment by lquigley** [comment]
I think this needs to be tagged as 1.0.1.

**Comment by vokal-isaac** [comment]
I think it needs to get merged upstream... which is my fault, sorry, doing that now.

**Comment by vokal-isaac** [comment]
[Should be done now](https://github.com/CocoaPods/Specs/tree/master/Specs/ILGHttpConstants).

**Pull request merged**
